name: CI/CD Node.js(pnpm)

on:
  push:
    branches: [ "main" ]   # chạy khi push lên main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # 6. Deploy dist/ + backend code
      - name: Deploy to server
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --delete
          path: |
            dist/
            package.json
            pnpm-lock.yaml
          remote_path: /var/www
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      # 8. Install dependencies production + restart PM2
      - name: Restart app with PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd /var/www
            pnpm install --prod || true
            pm2 restart server.js || pm2 start server.js
